# Jekyll Config
# https://jekyllrb.com/docs/configuration/

description: Bookmark this to keep an eye on my project updates!
gist:
  noscript: false
highlighter: rouge
incremental: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
lsi: false
safe: true
title: robdudeson's homepage
